services:

    db:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: tep
            #MYSQL_DATABASE: tep
        ports:
            - 3307:3306
        container_name: tepDB
        volumes:
             - .:/docker-entrypoint-initdb.d
    tomcat:
        # image: tomcat:8.0-jre8
        build: .
        restart: always
        environment:
            - JPDA_ADDRESS=7000
            - JPDA_TRANSPORT=dt_socket
        ports:
            - 8888:8080
            - 8443:8443
            - 9000:7000
        entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
        depends_on:
            - db
